### ISSUE TITLE
Align event storming items into the documentation or as an Issue if we need to discuss it

### ISSUE THREAD

**Issue by signekb** [seedcase-project/seedcase-sprout#1]
+ [x] User flow of Sprout (diagram) FOCUS #27 
+ [ ] Hold user flow up against event storming to ensure that we include everything we intended
+ [x] Create post documenting events in Sprout (general description of Sprout; things that are not in user flow) #27 
+ [X] Update sequence diagrams after user flow has been reviewed (Schema Creation and Data Upload) #22 
  - We have agreed to keep sequence out of date for now

**Comment by henrik-goul** [comment]
Here is also a link to the Figma file if that helps: https://www.figma.com/file/BIeKeC8MpYOWY74iq1ZNUU/Eventstorm-Recap?type=design&node-id=0%3A1&mode=design&t=CFIOSgjdISomvQXb-1
