### ISSUE TITLE
Create page for wireframe 2.1 and 2.2: Select Existing Table to add Data to storage (file and database)

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/seedcase-sprout#162]
We haven't gone this route yet too much, but since it connects well with the uploading files, we can start working on it.

@signekb:
There are these parts to this issue:
+ [X] Show metadata as rows in table with three buttons to `create new`, `edit existing`, or `add data`. #300 
+ [X] When selecting a row, expand to show the column metadata for the selected metadata. #307 
+ [X] Only show first 10 rows when expanding, and if more than 10 rows, have option to expand further. #359 
+ [X] Data Rows #379 
+ [X] Last Upload #379

**Comment by signekb** [comment]
There are three parts to this issue:
+ [X] Show metadata as rows in table with three buttons to `create new`, `edit existing`, or `add data`. #300 
+ [ ] When selecting a row, expand to show the column metadata for the selected metadata. #307 
+ [ ] Only show first 10 rows when expanding, and if more than 10 rows, have option to expand further.

**Comment by signekb** [comment]
All PR's connected to this issue has been merged.
